server:
    contextPath: ${hubcontentfeed.contextpath:/}
spring:
    data:
        mongodb:
            uri: ${hubcontentfeed.mongodb.connectionurl:mongodb://localhost:27017}
            database:  ${hubcontentfeed.mongodb.database:hub_metadata}
    main:
        banner-mode: off
    jackson:
        deserialization:
            fail-on-unknown-properties: ${hubcontentfeed.jackson.deserialization.enabled:false}
#Exposed Endpoints
endpoints:
    enabled: false
    health:
        enabled: ${hubcontentfeed.endpoints.health.enabled:true}
    metrics:
        enabled: ${hubcontentfeed.endpoints.metrics.enabled:true}
---
